language: node_js
cache:
    npm: false
node_js:
- lts/*
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: QxlWHAw85RgRhOuzVary1TEtebr68iSFzsVUJ4Xdsv0B9uLLCcxT2rgj//hNaqoRALNVFs2v6FuwXLqmk+rp394w68883AN+T3zY2qy83plqlVPXHd95oKsPFhJ0lv5FvuVBxzjrNR1t/rKSOxpuh2IqBqWPxYbrlNQ3kVnEB9jaaRQR7n7CMVYHJKYm2+RqlA8O4tVTUIoy2Vqm0fJ+q3uorz71m1U5vy6BD216PujvMGDDOnJR07QZxijsQKdDm03V4dKRLik1Aomb7N6uzzlMBaySwBMMJBRo5Lbb6dVWy9NT2wJk+HvdM9bwD/648qMMDoDBo8FNAfbexqTF/ZiSxCKGt+uQWxpEzOUOf18+hJay+ejhyi8D0D6USyrRK00HT8iW6R7fHmUM9QFOnZMLB2Tg6CHQol2qiIpJbLbp88sjO6VDcJdkDDmyvjWmiF2ce5g9/cIbRCr+obMIczoHMVfs3ZCSjonKPNklVaOcc5soITSVIJg9pdAo3AIU2SzUYHMLkiGAlyxdEXKYejXqNdLvDxkYXaKyyhaZw2qNgai4BVMe5HTRV4WUkrLUUBaDYZnOqDO0vn97t4cLLHf86C1Xx1D4h8yceq0NFAXtNhC5v/o8e82GjXmk7uk3ngW2DCyJQF5KqVh5U7uAFMHI/MneWvp+DurUp2VTblM=
