language: node_js
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: aNLRyazvXUZKn+crwT8QAbgotv+uU2H4KT8nnhxAHlFXC7dM9C48atg8aRfoVgPQXDvwmNasUhw5LpgfL4/mZzAs9eUaoJ0CIYfKTu/wmBXf3bbaf2NaRn/I5rWJUYPLicldHZcSTYRfIsSV501kGsO6L7h4eOhsDuxnG7VFCxV7A8a1b1kTccxg+v9V2usvW2Rz076rCXJi+ArhvaaPNMfBdXwWrh6/r9YH2I3saYdbKomchvKANr4c1NagriPrPdu7fk8gy9PGJvF7fmWuUVjUvBh/ssaANAK/ASOCPAszIs+rtZcCyq8Nmvkg5qxsZY2TJvJ6lQMpoSu4jCykTZGT/03H1OkiMQY8AowG30PYWNrT2eoYSKzsO1qTktUcKqHHiSux3UOqhOhSn3G107XH2vY1yj3eXnZDzTqoJqAZ0Cx2U3yLjZRUErTaC3n2AkRFGEfmjQTAqoqKbaeqfGh3EiPaX3N7vstQPUc6yEz5UbZ+/Hmmwhqe6PQ0FGcOHQ5A7LfuXKIGbFu/HJiGqMxcqquXasDpgXie1W5b00DOSe//CLoQvwaq3edECcKLuixV0CSBvMo7FlCCLASmwfSw0UmMlne4/WkaQtYkXJEOvz7YYzueEtHQ97f5MLlF9TMIIuMtWd8k6mT2P2T52aXuwUI2GeGmOG4zOatbD7A=
